<template>
  <div class="simple-pdf-page">
    <h1>Simple Property Report</h1>
    <div class="property-info">
      <h2>{{ address }}</h2>
      <p><strong>Date:</strong> {{ new Date().toLocaleDateString() }}</p>
      <p><strong>Coordinates:</strong> {{ lat }}, {{ lng }}</p>
    </div>
    
    <div class="section">
      <h3>Property Details</h3>
      <div v-if="property.lotDetails" class="property-details">
        <p><strong>Lot Plan:</strong> {{ property.lotDetails.lotplan }}</p>
        <p><strong>Suburb:</strong> {{ property.lotDetails.suburb }}</p>
        <p><strong>Local Government Area:</strong> {{ property.lotDetails.shire_name }}</p>
        <p v-if="property.lotDetails.lot_area"><strong>Land Area:</strong> {{ property.lotDetails.lot_area }} m²</p>
        <p><strong>Property Type:</strong> {{ property.lotDetails.tenure || 'Residential' }}</p>
      </div>
      <div v-else-if="isLoadingLotDetails">
        <p>Loading property details...</p>
      </div>
      <div v-else>
        <p>Property details not available</p>
      </div>
    </div>
    
    <div class="section">
      <h3>Property Overview</h3>
      <p>This is a simple test report for {{ address }}.</p>
      <ul>
        <li>Location verified</li>
        <li>Basic assessment complete</li>
        <li>Ready for detailed analysis</li>
      </ul>
    </div>
    
    <div class="section">
      <h3>Hazard Assessment</h3>
      <div class="hazard-grid">
        <div class="hazard-item">
          <strong>Flood Risk:</strong> 
          <span v-if="property.floodRisk && property.floodRisk.length > 0">
            {{ property.floodRisk[0].flood_risk || 'Unknown' }} 
            ({{ property.floodRisk[0].flood_type || 'Type unknown' }})
          </span>
          <span v-else>No flood risk detected</span>
        </div>
        
        <div class="hazard-item">
          <strong>Bushfire Risk:</strong>
          <span v-if="property.bushfireRisk && property.bushfireRisk.length > 0">
            {{ property.bushfireRisk[0].description || 'Unknown' }}
          </span>
          <span v-else>No bushfire risk detected</span>
        </div>
        
        <div class="hazard-item">
          <strong>Noise Risk:</strong>
          <span v-if="property.noiseRisk && property.noiseRisk.length > 0">
            {{ property.noiseRisk[0].description || 'Unknown' }}
          </span>
          <span v-else>No noise risk detected</span>
        </div>
        
        <div class="hazard-item">
          <strong>Coastal Erosion Risk:</strong>
          <span v-if="property.coastalErosionRisk && property.coastalErosionRisk.length > 0">
            {{ property.coastalErosionRisk[0].ovl2_desc || 'Unknown' }}
          </span>
          <span v-else>No coastal erosion risk detected</span>
        </div>
        
        <div class="hazard-item">
          <strong>Acid Sulfate Risk:</strong>
          <span v-if="property.acidSulfateRisk && property.acidSulfateRisk.length > 0">
            {{ property.acidSulfateRisk[0].acid_sulph || 'Unknown' }}
          </span>
          <span v-else>No acid sulfate risk detected</span>
        </div>
      </div>
    </div>
    
    <div class="section">
      <h3>Accessibility Assessment</h3>
      <div v-if="walkabilityData.score > 0" class="accessibility-content">
        <div class="walkability-score">
          <div class="score-display">
            <div class="score-circle" :class="getScoreColorClass(walkabilityData.score)">
              <span class="score-number">{{ walkabilityData.score }}</span>
            </div>
            <div class="score-description">
              <strong>Walkability Score</strong>
              <p class="score-text">{{ getScoreDescription(walkabilityData.score) }}</p>
            </div>
          </div>
        </div>
        
        <div class="accessibility-grid">
          <div v-for="item in walkabilityData.radarData" :key="item.name" class="accessibility-item">
            <strong>{{ item.name }}:</strong>
            <span :class="getAccessibilityRatingClass(item.value)">
              {{ getAccessibilityRatingText(item.value) }} ({{ item.value }}/20)
            </span>
          </div>
        </div>
        
        <div class="accessibility-summary">
          <p><strong>Total Points of Interest:</strong> {{ walkabilityData.totalPOIs }}</p>
          <p><strong>Assessment Area:</strong> 2 mile (3.2km) radius from property</p>
        </div>
      </div>
      <div v-else class="accessibility-loading">
        <p>Calculating accessibility score...</p>
      </div>
    </div>
    
    <div class="footer">
      <p>Generated by CliQ Property Analysis</p>
    </div>
  </div>
</template>

<script setup>
import { usePropertyData } from '~/composables/usePropertyData'
import { useWalkabilityScore } from '~/composables/useWalkabilityScore'
import { useWalkabilityState } from '~/composables/useWalkabilityState'
import { watch, ref, onMounted } from 'vue'
import * as turf from '@turf/turf'

const route = useRoute()
const address = route.query.address || 'Unknown Address'
const lat = route.query.lat || 'N/A'
const lng = route.query.lng || 'N/A'

// Check for walkability data passed via URL parameters first
const walkabilityScore = route.query.walkabilityScore ? parseInt(route.query.walkabilityScore) : 0
const walkabilityRadarData = route.query.walkabilityRadarData ? JSON.parse(decodeURIComponent(route.query.walkabilityRadarData)) : []
const walkabilityTotalPOIs = route.query.walkabilityTotalPOIs ? parseInt(route.query.walkabilityTotalPOIs) : 0

console.log('📥 PDF received walkability params:', { walkabilityScore, walkabilityRadarData, walkabilityTotalPOIs })

// Initialize property data
const { property, isLoadingLotDetails } = usePropertyData({
  address: '',
  lotDetails: null,
})

// Use shared walkability state
const { hasDataForCoordinates, getWalkabilityData, setWalkabilityData, setLoading, setError } = useWalkabilityState()
const { getWalkabilityScore } = useWalkabilityScore()

// Initialize walkability data - use URL params first, then cache, then calculate
const walkabilityData = ref({
  score: walkabilityScore,
  radarData: walkabilityRadarData,
  pieData: [],
  totalPOIs: walkabilityTotalPOIs,
  categories: {}
})

// Generate walkability area and get score only if not already provided via URL params
const calculateWalkability = async () => {
  // If we already have walkability data from URL parameters, don't recalculate
  if (walkabilityScore > 0 && walkabilityRadarData.length > 0) {
    console.log('✅ PDF: Using walkability data from URL parameters')
    return
  }
  
  const latNum = parseFloat(lat)
  const lngNum = parseFloat(lng)
  
  if (isNaN(latNum) || isNaN(lngNum)) {
    console.log('Invalid coordinates for walkability calculation')
    return
  }
  
  // Check if we already have data for these coordinates in cache
  if (hasDataForCoordinates(latNum, lngNum)) {
    const cachedData = getWalkabilityData(latNum, lngNum)
    if (cachedData) {
      walkabilityData.value = cachedData
      console.log('✅ PDF: Using cached walkability data:', cachedData)
      return
    }
  }
  
  console.log('🔄 PDF: Calculating new walkability data for coordinates:', latNum, lngNum)
  setLoading(true)
  
  try {
    // Create a circle with radius of 3.218km (2 miles) - same as AccessibilityCard
    const center = [lngNum, latNum]
    const radiusInKm = 3.218 // 2 miles in km - must match AccessibilityCard
    const options = { steps: 24, units: 'kilometers' }
    const circle = turf.circle(center, radiusInKm, options)
    const isochroneCoords = circle.geometry.coordinates
    
    // Get walkability data
    const result = await getWalkabilityScore(isochroneCoords)
    walkabilityData.value = result
    
    // Cache the result for future use
    setWalkabilityData(latNum, lngNum, result)
    
    // Console log the accessibility/walkability data
    console.log('Walkability Score:', result.score)
    console.log('Walkability Radar Data:', result.radarData)
    console.log('Walkability Categories:', result.categories)
    console.log('Total POIs found:', result.totalPOIs)
    
  } catch (error) {
    console.error('Error calculating walkability:', error)
    setError('Error calculating walkability')
  } finally {
    setLoading(false)
  }
}

// Console log property.floodRisk when it changes
watch(() => property.value.floodRisk, (newValue) => {
  console.log('property.floodRisk:', newValue)
}, { immediate: true })

// You can also log the entire property object
watch(() => property.value, (newValue) => {
  console.log('Full property object:', newValue)
}, { immediate: true, deep: true })

// Calculate walkability when component mounts and signal PDF ready after 3 seconds
onMounted(() => {
  if (lat !== 'N/A' && lng !== 'N/A') {
    // Start calculations immediately
    calculateWalkability()
  }
  
  // Signal PDF is ready after 3 seconds regardless of calculation status
  setTimeout(() => {
    console.log('🎯 PDF: Page ready for PDF generation after 3 seconds')
    // Set a data attribute on body to signal PDFShift the page is ready
    document.body.setAttribute('data-pdf-ready', 'true')
    // Dispatch a custom event that PDFShift can listen for
    window.dispatchEvent(new CustomEvent('pdfReady', { detail: { ready: true } }))
  }, 3000)
})

// Helper functions for accessibility display
const getScoreDescription = (score) => {
  if (score >= 108) return "Walker's Paradise" // 90% of 120
  if (score >= 84) return "Very Walkable" // 70% of 120
  if (score >= 60) return "Somewhat Walkable" // 50% of 120
  if (score >= 30) return "Car-Dependent" // 25% of 120
  return "Very Car-Dependent"
}

const getScoreColorClass = (score) => {
  if (score >= 96) return 'score-excellent' // 80% of 120
  if (score >= 72) return 'score-good' // 60% of 120
  if (score >= 48) return 'score-fair' // 40% of 120
  if (score >= 30) return 'score-poor' // 25% of 120
  return 'score-very-poor'
}

const getAccessibilityRatingText = (value) => {
  if (value >= 16) return 'Excellent'
  if (value >= 12) return 'Good'
  if (value >= 8) return 'Fair'
  if (value >= 4) return 'Poor'
  return 'Very Poor'
}

const getAccessibilityRatingClass = (value) => {
  if (value >= 16) return 'rating-excellent'
  if (value >= 12) return 'rating-good'
  if (value >= 8) return 'rating-fair'
  if (value >= 4) return 'rating-poor'
  return 'rating-very-poor'
}

// Set page title
useHead({
  title: `Property Report - ${address}`,
  meta: [
    { name: 'description', content: `Property report for ${address}` }
  ]
})
</script>

<style scoped>
.simple-pdf-page {
  max-width: 210mm;
  margin: 0 auto;
  padding: 20mm;
  font-family: Arial, sans-serif;
  background: white;
  color: black;
  line-height: 1.6;
}

h1 {
  color: #1a365d;
  font-size: 28px;
  margin-bottom: 20px;
  text-align: center;
}

h2 {
  color: #2d3748;
  font-size: 22px;
  margin-bottom: 15px;
}

h3 {
  color: #4a5568;
  font-size: 18px;
  margin-bottom: 10px;
  margin-top: 20px;
}

.property-info {
  background: #f7fafc;
  padding: 15px;
  border-radius: 8px;
  margin-bottom: 20px;
}

.section {
  margin-bottom: 20px;
  padding: 15px 0;
  border-bottom: 1px solid #e2e8f0;
}

.section:last-of-type {
  border-bottom: none;
}

ul {
  margin: 10px 0;
  padding-left: 20px;
}

li {
  margin: 5px 0;
}

.footer {
  margin-top: 30px;
  padding-top: 20px;
  border-top: 2px solid #1a365d;
  text-align: center;
  color: #718096;
  font-size: 14px;
}

.hazard-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 10px;
  margin: 15px 0;
}

.hazard-item {
  padding: 8px 12px;
  background: #f8f9fa;
  border-left: 4px solid #3182ce;
  border-radius: 4px;
}

.hazard-item strong {
  color: #2d3748;
  margin-right: 8px;
}

.property-details p {
  margin: 8px 0;
  padding: 5px 0;
}

.accessibility-content {
  margin: 15px 0;
}

.walkability-score {
  margin-bottom: 20px;
}

.score-display {
  display: flex;
  align-items: center;
  gap: 15px;
  margin-bottom: 15px;
}

.score-circle {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  border: 3px solid;
}

.score-number {
  font-size: 20px;
  font-weight: bold;
}

.score-description {
  flex: 1;
}

.score-text {
  margin: 5px 0 0 0;
  font-size: 14px;
  color: #666;
}

.score-excellent {
  background: #dcfce7;
  border-color: #16a34a;
  color: #16a34a;
}

.score-good {
  background: #dbeafe;
  border-color: #2563eb;
  color: #2563eb;
}

.score-fair {
  background: #fef3c7;
  border-color: #d97706;
  color: #d97706;
}

.score-poor {
  background: #fed7d7;
  border-color: #dc2626;
  color: #dc2626;
}

.score-very-poor {
  background: #fee2e2;
  border-color: #991b1b;
  color: #991b1b;
}

.accessibility-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 8px;
  margin: 15px 0;
}

.accessibility-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 12px;
  background: #f8f9fa;
  border-left: 4px solid #6366f1;
  border-radius: 4px;
}

.accessibility-item strong {
  color: #2d3748;
  margin-right: 8px;
}

.rating-excellent {
  color: #16a34a;
  background: #dcfce7;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}

.rating-good {
  color: #2563eb;
  background: #dbeafe;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}

.rating-fair {
  color: #d97706;
  background: #fef3c7;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}

.rating-poor {
  color: #dc2626;
  background: #fed7d7;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}

.rating-very-poor {
  color: #991b1b;
  background: #fee2e2;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}

.accessibility-summary {
  margin-top: 15px;
  padding-top: 10px;
  border-top: 1px solid #e2e8f0;
  font-size: 14px;
}

.accessibility-summary p {
  margin: 5px 0;
}

.accessibility-loading {
  text-align: center;
  color: #666;
  font-style: italic;
}

/* Print styles */
@media print {
  .simple-pdf-page {
    margin: 0;
    padding: 15mm;
  }
  
  .hazard-item, .accessibility-item {
    break-inside: avoid;
  }
  
  .score-display {
    break-inside: avoid;
  }
}
</style>
