<template>
  <div class="simple-pdf-page">
    <h1>Simple Property Report</h1>
    <div class="property-info">
      <h2>{{ address }}</h2>
      <p><strong>Date:</strong> {{ new Date().toLocaleDateString() }}</p>
      <p><strong>Coordinates:</strong> {{ lat }}, {{ lng }}</p>
    </div>
    
    <div class="section">
      <h3>Property Overview</h3>
      <p>This is a simple test report for {{ address }}.</p>
      <ul>
        <li>Location verified</li>
        <li>Basic assessment complete</li>
        <li>Ready for detailed analysis</li>
      </ul>
    </div>
    
    <div class="section">
      <h3>Test Information</h3>
      <p>This page is designed to test PDF generation with PDFShift.</p>
      <p>No complex JavaScript or external resources are loaded.</p>
    </div>
    
    <div class="footer">
      <p>Generated by CliQ Property Analysis</p>
    </div>
  </div>
</template>

<script setup>
const route = useRoute()
const address = route.query.address || 'Unknown Address'
const lat = route.query.lat || 'N/A'
const lng = route.query.lng || 'N/A'

// Set page title
useHead({
  title: `Simple Report - ${address}`,
  meta: [
    { name: 'description', content: `Simple property report for ${address}` }
  ]
})
</script>

<style scoped>
.simple-pdf-page {
  max-width: 210mm;
  margin: 0 auto;
  padding: 20mm;
  font-family: Arial, sans-serif;
  background: white;
  color: black;
  line-height: 1.6;
}

h1 {
  color: #1a365d;
  font-size: 28px;
  margin-bottom: 20px;
  text-align: center;
}

h2 {
  color: #2d3748;
  font-size: 22px;
  margin-bottom: 15px;
}

h3 {
  color: #4a5568;
  font-size: 18px;
  margin-bottom: 10px;
  margin-top: 20px;
}

.property-info {
  background: #f7fafc;
  padding: 15px;
  border-radius: 8px;
  margin-bottom: 20px;
}

.section {
  margin-bottom: 20px;
  padding: 15px 0;
  border-bottom: 1px solid #e2e8f0;
}

.section:last-of-type {
  border-bottom: none;
}

ul {
  margin: 10px 0;
  padding-left: 20px;
}

li {
  margin: 5px 0;
}

.footer {
  margin-top: 30px;
  padding-top: 20px;
  border-top: 2px solid #1a365d;
  text-align: center;
  color: #718096;
  font-size: 14px;
}

/* Print styles */
@media print {
  .simple-pdf-page {
    margin: 0;
    padding: 15mm;
  }
}
</style>
